# Exploratory data analysis for Neighborhoods in Auckland
**A Capstone Project - The Battle of Neighborhoods**

Based on the Neighborhood and Crime Location data in Auckland, this project is 

## Introduction

Auckland(Tāmaki Makaurau) is the biggest city in New Zealand, with the population growing, the crimes happening frequency is increasing too. 
This project is to help people who migrate to Auckland to know more about the neighborhoods in Auckland.

### Current Problems
In Auckland, neighborhood and neighborhood are very different, some neighborhood is quite, some are busy. 
With the population growing, the crime frequency and safety of neighborhood are changing too. 
For example, Albany was the place for trash land filling, but now more and more houses are built, at the same time land price increased too.
New Zealand Police published the crime dataset on its website, but the problem there is no easy and direct way to know about the neighborhoods' safety.
This project is to help to solve this problem to let the residents and new migrants in Auckland to know about their neighborhoods.

### Dataset Required

New Zealand goverment provides crime data which is public, to build this project, there are 2 data sets required.
- `NZ Crimes Data`
- `Neighborhood Coordinate Data`

The crime dataset can be easily gotten from NZ Police Website, but they do not offer a neighborhood and coordinate dataset.
To get the coordinate data, we can use `geopy`'s Nominatim function to call Open Street Map geocode api. 
There might be a problem to use this method that there is a limit for the api usage. In this project, we generated a JSON file to build a dictionary of neighborhood and coordinates.

#### Neighborhood Data Preparation
The first data can be easily got through `police.govt.nz`. There is more than 400 neighborhood in Auckland. It is easy to get time out error when getting location through `geopy` geocoder. To fix this problem, the `locations_2020.sjon` file is used. This json file contains all location data required for this project.

To generate this file, each API calling of the geocoder is waited by 1 or 2 seconds, and every about 60 to 90 api calls are run separatelly and manuelly.


## References
- [Police Stat](https://www.police.govt.nz/about-us/publications-statistics/data-and-statistics)
- [Foursquare API](https://developer.foursquare.com/)
- [geopy](https://www.police.govt.nz/about-us/publications-statistics/data-and-statistics)

## Table of Contents
1. Data Preparation

## 1 Data Preparation

### 1.1 Prepare Python Dependecies

In [1]:
# instead of use request to call foursquare api, use this python client
!pip install foursquare

In [2]:
# other packages required here
!conda install -c conda-forge geopy matplotlib python-dotenv folium=0.5.0 --yes 

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.5.11
  latest version: 4.8.2

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/jupyterlab/conda/envs/python

  added / updated specs: 
    - folium=0.5.0
    - geopy
    - matplotlib
    - python-dotenv


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2019.11.28         |           py36_0         149 KB  conda-forge
    scikit-learn-0.20.1        |   py36h22eb022_0         5.7 MB
    pyqt-5.6.0                 |py36h13b7fb3_1008         5.4 MB  conda-forge
    liblapack-3.8.0            |      11_openblas          10 KB  conda-forge
    sip-4.18.1                 |py36hf484d3e_1000         277 KB  conda-forge
    numpy-1.18.1               |   py36h95a1406_0         5.2 MB  conda-forge
    python-doten

### 1.2 Prepare Crimes Data

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('./NZ_Crimes.csv')

In [5]:
df_akl = df[df['Territorial Authority']=='Auckland.']

columns=[
    'ANZSOC Division',
    'ANZSOC Group',
    'ANZSOC Subdivision',
    'Area Unit',
    'Locn Type Division',
    'Meshblock',
    'Occurrence Day Of Week',
    'Occurrence Hour Of Day',
    'Weapon',
    ' Month Year',
]

df_akl=df_akl[columns].astype({
    'Meshblock': 'int32',
    'Occurrence Hour Of Day': 'int32',
})

# formate the date (Month Year), using date instead of string
from datetime import datetime
df_akl[' Month Year']=df_akl[' Month Year'].apply(
    lambda x: datetime.strptime(x, '%B %Y')
)

df_akl = df_akl.rename(columns={
    ' Month Year': 'YearMonth'
})

df_akl.head()

ANZSOC Division                ANZSOC Group  \
24  Theft and Related Offences  Theft From Retail Premises   
25  Theft and Related Offences  Theft From Retail Premises   
26  Theft and Related Offences  Theft From Retail Premises   
27  Theft and Related Offences  Theft From Retail Premises   
28  Theft and Related Offences  Theft From Retail Premises   

               ANZSOC Subdivision               Area Unit Locn Type Division  \
24  Theft (Except Motor Vehicles)                 Albany.     Other Location   
25  Theft (Except Motor Vehicles)  Auckland Central West.     Other Location   
26  Theft (Except Motor Vehicles)  Auckland Central West.     Other Location   
27  Theft (Except Motor Vehicles)  Auckland Central West.     Other Location   
28  Theft (Except Motor Vehicles)    Mt Wellington South.     Other Location   

    Meshblock Occurrence Day Of Week  Occurrence Hour Of Day          Weapon  \
24     178900               Saturday                      15  Not Applicable   
25     433501               Saturday                      15  Not Applicable   
26     433600               Saturday                      15  Not Applicable   
27     434000               Saturday                      15  Not Applicable   
28     637400               Saturday                      15  Not Applicable   

    YearMonth  
24 2019-01-01  
25 2019-01-01  
26 2019-01-01  
27 2019-01-01  
28 2019-01-01

In [6]:
df_akl.dtypes

ANZSOC Division                   object
ANZSOC Group                      object
ANZSOC Subdivision                object
Area Unit                         object
Locn Type Division                object
Meshblock                          int32
Occurrence Day Of Week            object
Occurrence Hour Of Day             int32
Weapon                            object
YearMonth                 datetime64[ns]
dtype: object

In [7]:
rows_num = df_akl.shape[0]
print('crimed date is loaded and prepared, totally {} rows'.format(rows_num))

crimed date is loaded and prepared, totally 74156 rows


### 1.2 Prepare Location Data

the way to get the latitude and longitude for each suburbs (area names)
```
from geopy.geocoders import Nominatim
geolocator = Nominatim(user_agent="akl_spider")
location = geolocator.geocode("{} auckland new zealand".format('albany'))
```
the way generated the `area_location.json` notebook.
```
with open('area_location.json', 'w') as file:
    json.dump(area_dict, file)
```

loading the generated json file instead of run the geocode each time will increase notebook speadd siginifitantly.


In [8]:
import json
areas = list(df_akl['Area Unit'].unique())
# this json file contains suburbs of Auckland
## which is generated through calling geopy geocode function
## it is too heavy to call it every time to run the notebook, so the json file is generated
# some one which cannot get through 'geocoder' which will be set to (0,0)
# for example `Inlet-Waitemata Harbour` which is not a correct suburb in Auckland, this kind of rows will be droped in this step

locations_2020 = {}
with open('locations_2020.json', 'r') as file:
    locations_2020=json.load(file)

In [9]:
if (len(locations_2020.keys()) < len(areas)):
    # the json file loades seems like outdated
    from geopy.geocoders import Nominatim
    import time
    locations = []

    def get_location(area_name, ua="Mozilla/5.0 (X11; Linux i686; rv:67.0) Gecko/20100101 Firefox/67.0"):
        geolocator = Nominatim(user_agent=ua)
        location = geolocator.geocode("{} auckland new zealand".format(area_name))
        time.sleep(1)
        return location

    def get_locations(area_names):
        return list(map(get_location, area_names))

    # runing this too fast will cause time out error
    # better to run the codes below in separate cells manuelly
    locations += get_locations(areas[:50])
    locations += get_locations(areas[50:100])
    locations += get_locations(areas[100:180])
    locations += get_locations(areas[180:260])
    locations += get_locations(areas[260:350])
    locations += get_locations(areas[350:400])
    locations += get_locations(areas[400:])
    locations_2020 = locations
else:
    print('locations is imported through loading json file')

locations is imported through loading json file


In [10]:
# a simple test to make sure the json is loaded correctly
print('json loading successfully ' if 'Albany.' in locations_2020.keys() and len(locations_2020.keys()) >= len(areas) else '') 

json loading successfully 


In [11]:
df_akl['latitude'] = df_akl['Area Unit'].apply(lambda x: locations_2020[x][0])
df_akl['longitude'] = df_akl['Area Unit'].apply(lambda x: locations_2020[x][1])

df_akl = df_akl[df_akl['latitude']!=0]

In [12]:
rows_num_after_drop = df_akl.shape[0]

In [13]:
df_akl.head()

ANZSOC Division                ANZSOC Group  \
24  Theft and Related Offences  Theft From Retail Premises   
25  Theft and Related Offences  Theft From Retail Premises   
26  Theft and Related Offences  Theft From Retail Premises   
27  Theft and Related Offences  Theft From Retail Premises   
28  Theft and Related Offences  Theft From Retail Premises   

               ANZSOC Subdivision               Area Unit Locn Type Division  \
24  Theft (Except Motor Vehicles)                 Albany.     Other Location   
25  Theft (Except Motor Vehicles)  Auckland Central West.     Other Location   
26  Theft (Except Motor Vehicles)  Auckland Central West.     Other Location   
27  Theft (Except Motor Vehicles)  Auckland Central West.     Other Location   
28  Theft (Except Motor Vehicles)    Mt Wellington South.     Other Location   

    Meshblock Occurrence Day Of Week  Occurrence Hour Of Day          Weapon  \
24     178900               Saturday                      15  Not Applicable   
25     433501               Saturday                      15  Not Applicable   
26     433600               Saturday                      15  Not Applicable   
27     434000               Saturday                      15  Not Applicable   
28     637400               Saturday                      15  Not Applicable   

    YearMonth   latitude   longitude  
24 2019-01-01 -36.727058  174.698055  
25 2019-01-01 -36.848911  174.765226  
26 2019-01-01 -36.848911  174.765226  
27 2019-01-01 -36.848911  174.765226  
28 2019-01-01 -36.904793  174.835118

In [14]:
print('there {} rows which does not have a clean area name'.format(rows_num - rows_num_after_drop))
print('now we have {} rows in the table for the next step'.format(rows_num_after_drop))

there 4649 rows which does not have a clean area name
now we have 69507 rows in the table for the next step


### 1.3 Prepare Data For folium

In [15]:
# clean this area unit which can be found in geocode, but which is not a correct area name in Auckland
df_akl = df_akl[df_akl['Area Unit'] != '-29']

In [16]:
df_borough= df_akl.groupby('Area Unit').mean()
# df_borough['Crime Count']=df_akl.groupby('Area Unit').count()['YearMonth']

In [17]:
df_borough['CrimeCount'] = df_akl.groupby('Area Unit').count()['YearMonth']

In [18]:
df_borough=df_borough.drop(['Meshblock', 'Occurrence Hour Of Day'], axis=1).reset_index().rename(columns={'Area Unit': 'Neighborhood'})

## 2 Cluster neighborhood in Auckland by location

In [19]:
from sklearn.cluster import KMeans
# set number of clusters
kclusters = 10

df_to_cluster = df_borough.drop(['Neighborhood','CrimeCount'], 1)

# run k-means clustering
kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(df_to_cluster)

# check cluster labels generated for each row in the dataframe
kmeans.labels_[0:10] 

array([9, 3, 6, 0, 0, 7, 9, 7, 3, 9], dtype=int32)

In [20]:
# join cluster label to the data framke
df_inserted = df_borough
df_inserted.insert(0, 'Cluster Labels', kmeans.labels_)


In [21]:
df_inserted.head()

Cluster Labels Neighborhood   latitude   longitude  CrimeCount
0               9     Akarana. -36.904895  174.745517         226
1               3      Albany. -36.727058  174.698055         829
2               6  Algies Bay. -36.432677  174.736948          10
3               0      Ambury. -36.949533  174.770149          51
4               0      Aorere. -36.980988  174.832658         111

In [22]:
import pandas as pd
from sklearn import preprocessing
# scale the CrimeCount to 0 to 1

x = df_inserted[['CrimeCount']] #returns a numpy array
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)
df_scaled = pd.DataFrame(x_scaled)

/home/jupyterlab/conda/envs/python/lib/python3.6/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype int64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)


In [23]:
df_inserted.insert(0, 'CrimeCountScaler', df_scaled[0])
df_inserted.head()

CrimeCountScaler  Cluster Labels Neighborhood   latitude   longitude  \
0          0.098039               9     Akarana. -36.904895  174.745517   
1          0.360784               3      Albany. -36.727058  174.698055   
2          0.003922               6  Algies Bay. -36.432677  174.736948   
3          0.021786               0      Ambury. -36.949533  174.770149   
4          0.047930               0      Aorere. -36.980988  174.832658   

   CrimeCount  
0         226  
1         829  
2          10  
3          51  
4         111

In [31]:
import folium
import matplotlib.cm as cm
import matplotlib.colors as colors

# create map
map_clusters = folium.Map(location=[-36.8485,174.7633], zoom_start=11)

# set color scheme for the clusters
x = np.arange(kclusters)
ys = [i + x + (i*x)**2 for i in range(kclusters)]
colors_array = cm.rainbow(np.linspace(0, 1, len(ys)))
rainbow = [colors.rgb2hex(i) for i in colors_array]

# add markers to the map
markers_colors = []
for lat, lon, poi, cluster, scaler in zip(df_inserted['latitude'], df_inserted['longitude'], df_inserted['Neighborhood'], df_inserted['Cluster Labels'], df_inserted['CrimeCountScaler']):
    label = folium.Popup(str(poi) + ' Cluster ' + str(cluster), parse_html=True)
    folium.CircleMarker(
        [lat, lon],
        radius= 4+10*scaler, # change the marker size here
        popup=label,
        color=rainbow[cluster-1],
        fill=True,
        fill_color=rainbow[cluster-1],
        fill_opacity=0.7).add_to(map_clusters)

map_clusters

Print out the head of clusters with crime count

In [32]:
for i in range(0, kclusters):
    cluster = df_inserted[df_inserted['Cluster Labels'] == i]
    print('##### {} rows in cluster {} #####'.format(cluster.shape[0], i))
    print(cluster.sample(frac=0.05))
    print('\n')

##### 92 rows in cluster 0 #####
     CrimeCountScaler  Cluster Labels      Neighborhood   latitude  \
55           0.089760               0  Ellerslie North. -36.897603   
177          0.105447               0        Millhouse. -36.914947   
120          0.098911               0   Howick Central. -36.923809   
99           0.046187               0     Harania East. -36.951714   
344          0.042702               0         Viscount. -36.969339   

      longitude  CrimeCount  
55   174.815030         207  
177  174.918474         243  
120  174.899416         228  
99   174.812508         107  
344  174.790124          99  


##### 12 rows in cluster 1 #####
     CrimeCountScaler  Cluster Labels  Neighborhood   latitude  longitude  \
104          0.044444               1  Helensville. -36.679921  174.45054   

     CrimeCount  
104         103  


##### 61 rows in cluster 2 #####
     CrimeCountScaler  Cluster Labels    Neighborhood   latitude   longitude  \
321          0.006972    

## 3 Prepare Venue Data 
calling foursquare api to get the related venues for each suburbs

In [26]:
%load_ext dotenv
%dotenv

**Please set up the `.env` firstly** before running the cell below.

In [27]:
import os
import foursquare
client_id = os.environ['CLIENT_ID']
client_secret=os.environ['CLIENT_SECRET']
version=os.environ['VERSION']

In [28]:
import requests
from pandas.io.json import json_normalize

# define a function to get the foursquare result
def get_venue(lat, lng, radius, limit):

    url = 'https://api.foursquare.com/v2/venues/explore?&client_id={}&client_secret={}&v={}&ll={},{}&radius={}&limit={}'.format(
        client_id, 
        client_secret, 
        version, 
        lat, 
        lng, 
        radius, 
        limit)
#     client = foursquare.Foursquare(client_id=client_id, client_secret=client_secret, version=version)
    results = requests.get(url).json()["response"]['groups'][0]['items']
#     results = client.venues.explore({
#         'll':(lat,lng)
#     })
    return results
get_venue(-36.727, 174.698, 500, 10)

# try use foursquare client package instead

[{'reasons': {'count': 0,
   'items': [{'summary': 'This spot is popular',
     'type': 'general',
     'reasonName': 'globalInteractionReason'}]},
  'venue': {'id': '4b6f9a64f964a5208df72ce3',
   'name': 'QBE Stadium',
   'location': {'address': 'Oteha Valley Road',
    'lat': -36.726937342858996,
    'lng': 174.70205945588367,
    'labeledLatLngs': [{'label': 'display',
      'lat': -36.726937342858996,
      'lng': 174.70205945588367}],
    'distance': 362,
    'postalCode': '0632',
    'cc': 'NZ',
    'neighborhood': 'North Harbour',
    'city': 'North Shore',
    'state': 'Auckland',
    'country': 'New Zealand',
    'formattedAddress': ['Oteha Valley Road',
     'North Shore 0632',
     'New Zealand']},
   'categories': [{'id': '4bf58dd8d48988d184941735',
     'name': 'Stadium',
     'pluralName': 'Stadiums',
     'shortName': 'Stadium',
     'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/arts_entertainment/stadium_',
      'suffix': '.png'},
     'primary': True}],
 

try use the `get_venue` to get result of `albany` (-36.727058 	174.698055)

In [29]:
albany_lat_lng = (-36.727058, 174.698055)
get_venue(albany_lat_lng[0], albany_lat_lng[1], 500, 100)

[{'reasons': {'count': 0,
   'items': [{'summary': 'This spot is popular',
     'type': 'general',
     'reasonName': 'globalInteractionReason'}]},
  'venue': {'id': '4b6f9a64f964a5208df72ce3',
   'name': 'QBE Stadium',
   'location': {'address': 'Oteha Valley Road',
    'lat': -36.726937342858996,
    'lng': 174.70205945588367,
    'labeledLatLngs': [{'label': 'display',
      'lat': -36.726937342858996,
      'lng': 174.70205945588367}],
    'distance': 357,
    'postalCode': '0632',
    'cc': 'NZ',
    'neighborhood': 'North Harbour',
    'city': 'North Shore',
    'state': 'Auckland',
    'country': 'New Zealand',
    'formattedAddress': ['Oteha Valley Road',
     'North Shore 0632',
     'New Zealand']},
   'categories': [{'id': '4bf58dd8d48988d184941735',
     'name': 'Stadium',
     'pluralName': 'Stadiums',
     'shortName': 'Stadium',
     'icon': {'prefix': 'https://ss3.4sqi.net/img/categories_v2/arts_entertainment/stadium_',
      'suffix': '.png'},
     'primary': True}],
 